[default]
key = "56eada1252c02c8c4217a9a8a527a9c1"

[development]
api_url = "http://api.openweathermap.org/data/2.5/"
use_mock = true

[production]
api_url = "http://api.openweathermap.org/data/2.5/"
use_mock = false